# Generated by Django 6.1 on 2026-08-10 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', editable=False, max_length=20)),
                ('starter_code', models.TextField(blank=True)),
                ('public_test_description', models.TextField(blank=True)),
                ('hidden_test_ids', models.JSONField(blank=True, default=list)),
                ('transfer_prompt', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exercise', to='learning_core.learningactivity')),
            ],
        ),
    ]
