# Generated by Django 6.1 on 2026-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSubjectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('DEFINITION', 'Definition'), ('COMPARISON', 'Comparison or classification'), ('EVIDENCE', 'Evidence-based response')], max_length=24)),
                ('reference_answer', models.TextField(blank=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
