# Generated by Django 6.1 on 2026-08-16 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_quiz', '0002_sample_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_session_key', models.CharField(db_index=True, max_length=40)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='other_quiz.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question', 'browser_session_key'), name='unique_other_quiz_question_browser')],
            },
        ),
    ]
