# Generated by Django 6.1 on 2026-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_quiz', '0002_auto_20260814_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
