"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from .environment import env_bool, env_csv, require_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development').strip().lower()
if ENVIRONMENT not in {'development', 'production'}:
    raise ImproperlyConfigured('DJANGO_ENV must be development or production.')

IS_PRODUCTION = ENVIRONMENT == 'production'
DEBUG = env_bool('DJANGO_DEBUG', not IS_PRODUCTION)

SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()
if IS_PRODUCTION:
    SECRET_KEY = require_env('SECRET_KEY')
    if len(SECRET_KEY) < 50:
        raise ImproperlyConfigured('SECRET_KEY must contain at least 50 characters in production.')
elif not SECRET_KEY:
    SECRET_KEY = 'unsafe-local-demo-only'

render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
default_allowed_hosts = ('127.0.0.1', 'localhost') if not IS_PRODUCTION else ()
if render_hostname:
    default_allowed_hosts = (*default_allowed_hosts, render_hostname)

ALLOWED_HOSTS = env_csv('DJANGO_ALLOWED_HOSTS', default=default_allowed_hosts)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS is required in production.')
if IS_PRODUCTION and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS cannot contain * in production.')

default_csrf_trusted_origins = (f'https://{render_hostname}',) if render_hostname else ()
CSRF_TRUSTED_ORIGINS = env_csv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default=default_csrf_trusted_origins,
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core.apps.CoreConfig',
    'apps.ai_engine.apps.AiEngineConfig',
    'apps.learning_core.apps.LearningCoreConfig',
    'apps.progress.apps.ProgressConfig',
    'apps.math_quiz.apps.MathQuizConfig',
    'apps.coding_quiz.apps.CodingQuizConfig',
    'apps.code_runner.apps.CodeRunnerConfig',
    'apps.lang_quiz.apps.LangQuizConfig',
    'apps.other_quiz.apps.OtherQuizConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Must run before LocaleMiddleware — see its docstring: makes
    # LANGUAGE_CODE the real default for new visitors instead of the
    # browser's Accept-Language header silently overriding it.
    'config.middleware.IgnoreBrowserLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE == 'mysql':
    if IS_PRODUCTION:
        for required_database_setting in ('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST'):
            require_env(required_database_setting)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'ai_thinking'),
            'USER': os.environ.get('DB_USER', 'ai_thinking_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'isolation_level': 'read committed',
            },
        }
    }
elif DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured('DB_ENGINE must be sqlite or mysql.')


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('ja', '日本語'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if IS_PRODUCTION
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# Browser and transport security. HSTS preload remains opt-in because enabling it is difficult
# to reverse; production enables a one-hour HSTS rollout by default.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', IS_PRODUCTION)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', IS_PRODUCTION)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '3600' if IS_PRODUCTION else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    IS_PRODUCTION,
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)

if env_bool('DJANGO_TRUST_PROXY_HEADERS', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CODE_RUNNER_URL = os.environ.get(
    'CODE_RUNNER_URL',
    '' if IS_PRODUCTION else 'http://127.0.0.1:8765',
)
CODE_RUNNER_AUTH_TOKEN = os.environ.get('CODE_RUNNER_AUTH_TOKEN', '')
CODE_RUNNER_REQUIRED = env_bool('CODE_RUNNER_REQUIRED', IS_PRODUCTION)
CODE_RUNNER_TIMEOUT_SECONDS = int(os.environ.get('CODE_RUNNER_TIMEOUT_SECONDS', '40'))
CODE_RUNNER_AUTOSTART = env_bool('CODE_RUNNER_AUTOSTART', not IS_PRODUCTION)
CODE_RUNNER_AUTOSTART_TIMEOUT_SECONDS = int(os.environ.get('CODE_RUNNER_AUTOSTART_TIMEOUT_SECONDS', '75'))
if IS_PRODUCTION and CODE_RUNNER_REQUIRED:
    CODE_RUNNER_URL = require_env('CODE_RUNNER_URL')
    CODE_RUNNER_AUTH_TOKEN = require_env('CODE_RUNNER_AUTH_TOKEN')
# An explicit AI_PROVIDER_CLASS still names exactly one provider class,
# same as before (many tests override this to force a single provider —
# see apps/ai_engine/tests.py, apps/coding_quiz/tests.py). Left
# unset, it now points at FallbackProvider whenever *any* provider key is
# configured — FallbackProvider itself builds the real DeepSeek -> Gemini
# -> Groq chain from whichever keys are present (see
# apps/ai_engine/providers/fallback.py), so a single failing provider (out
# of quota, a deprecated model name, ...) no longer takes AI assistance
# down entirely when another one is available.
AI_PROVIDER_CLASS = os.environ.get('AI_PROVIDER_CLASS') or (
    'apps.ai_engine.providers.fallback.FallbackProvider'
    if (
        os.environ.get('DEEPSEEK_API_KEY')
        or os.environ.get('GEMINI_API_KEY')
        or os.environ.get('GROQ_API_KEY')
    )
    else ''
)
AI_CONTEXT_POLICY = 'privacy_minimized'
# 'gemini-2.5-flash' (a pinned version) was retired for new callers —
# 'gemini-flash-latest' is Google's unpinned alias to the current default
# flash model, so it doesn't go stale the same way a pinned version does.
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-flash-latest')
GEMINI_TIMEOUT_SECONDS = int(os.environ.get('GEMINI_TIMEOUT_SECONDS', '20'))
DEEPSEEK_MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-v4-flash')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_TIMEOUT_SECONDS = int(os.environ.get('DEEPSEEK_TIMEOUT_SECONDS', '20'))
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama-3.3-70b-versatile')
GROQ_TIMEOUT_SECONDS = int(os.environ.get('GROQ_TIMEOUT_SECONDS', '20'))

if 'test' in sys.argv:
    AI_PROVIDER_CLASS = ''
    CODE_RUNNER_URL = ''
    CODE_RUNNER_GATEWAY_CLASS = ''
    CODE_RUNNER_AUTOSTART = False


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_ENABLED = env_bool('EMAIL_ENABLED', IS_PRODUCTION)
if IS_PRODUCTION and EMAIL_ENABLED:
    email_use_tls = env_bool('EMAIL_USE_TLS', True)
    email_use_ssl = env_bool('EMAIL_USE_SSL', False)
    if email_use_tls and email_use_ssl:
        raise ImproperlyConfigured('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be true.')
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': require_env('EMAIL_HOST'),
                'port': int(os.environ.get('EMAIL_PORT', '587')),
                'username': os.environ.get('EMAIL_HOST_USER', ''),
                'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
                'use_tls': email_use_tls,
                'use_ssl': email_use_ssl,
                'timeout': int(os.environ.get('EMAIL_TIMEOUT', '10')),
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'config.email_backend.DisabledEmailBackend'
            if IS_PRODUCTION
            else 'django.core.mail.backends.console.EmailBackend',
        },
    }

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@localhost')
