"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from django.db.backends.signals import connection_created

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') or 'unsafe-local-demo-only'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core.apps.CoreConfig',
    'apps.ai_engine.apps.AiEngineConfig',
    'apps.learning_core.apps.LearningCoreConfig',
    'apps.progress.apps.ProgressConfig',
    'apps.math_quiz.apps.MathQuizConfig',
    'apps.coding_quiz.apps.CodingQuizConfig',
    'apps.code_runner.apps.CodeRunnerConfig',
    'apps.lang_quiz.apps.LangQuizConfig',
    'apps.other_quiz.apps.OtherQuizConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Must run before LocaleMiddleware — see its docstring: makes
    # LANGUAGE_CODE the real default for new visitors instead of the
    # browser's Accept-Language header silently overriding it.
    'config.middleware.IgnoreBrowserLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite's default rollback-journal mode takes an exclusive lock on
        # the whole file for any write, so two requests writing around the
        # same time easily trip "database is locked" under Django's default
        # 5s wait — bump that wait here, and switch to WAL mode below
        # (readers no longer block writers, which is most of what this app
        # actually does concurrently). 60s because some of this app's writes
        # sit behind a slow/retried AI API call (see services.py's various
        # @transaction.atomic functions) — the most AI-call-heavy of those
        # are being restructured to not hold the lock during the AI call at
        # all, but this stays as a safety margin for the rest.
        #
        # transaction_mode='IMMEDIATE': Django's sqlite backend otherwise
        # opens atomic() blocks with plain "BEGIN" (DEFERRED), which only
        # takes a read lock up front. If two concurrent transactions each
        # then try to upgrade to a write lock, that upgrade race raises
        # "database is locked" immediately — busy_timeout only governs the
        # wait for an *initial* lock, not this upgrade conflict. IMMEDIATE
        # takes the write lock at BEGIN, so a second writer just queues
        # (and correctly waits out busy_timeout) instead of racing.
        'OPTIONS': {'timeout': 60, 'transaction_mode': 'IMMEDIATE'},
    }
}


def _enable_sqlite_wal_mode(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute('PRAGMA journal_mode=WAL;')
            cursor.execute('PRAGMA busy_timeout=60000;')


connection_created.connect(_enable_sqlite_wal_mode)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('ja', '日本語'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CODE_RUNNER_URL = os.environ.get('CODE_RUNNER_URL', '')
CODE_RUNNER_AUTH_TOKEN = os.environ.get('CODE_RUNNER_AUTH_TOKEN', '')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
