# Generated by Django 6.1 on 2026-08-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='units/'),
        ),
    ]
