# Generated by Django 6.1 on 2026-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0003_unit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='advanced_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='definitions_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='examples_content',
            field=models.TextField(blank=True),
        ),
    ]
