# Generated by Django 6.1 on 2026-08-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0004_unit_advanced_content_unit_definitions_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='advanced_content',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='definitions_content',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='examples_content',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='math_quiz.unit')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('answer', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='math_quiz.section')),
            ],
        ),
    ]
