# Generated by Django 6.1 on 2026-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0005_remove_unit_advanced_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
