# Generated by Django 6.1 on 2026-08-11 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0006_attempt_explanation_attempt_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='diagnosis_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='revision_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='suspected_misconception',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attempt',
            name='verification_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='verification_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='math_quiz.attempt')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_session_key', models.CharField(db_index=True, max_length=40)),
                ('current_state', models.CharField(choices=[('DIAGNOSTIC_QUIZ', 'Diagnostic quiz'), ('FIRST_ATTEMPT', 'First attempt'), ('DIAGNOSIS', 'Diagnosis'), ('VERIFICATION', 'Verification'), ('GUIDED_REVISION', 'Guided revision'), ('TEACH_BACK', 'Teach-Back'), ('TRANSFER_TASK', 'Transfer task'), ('MASTERED', 'Mastered'), ('NEEDS_REVIEW', 'Needs review')], default='DIAGNOSTIC_QUIZ', max_length=32)),
                ('first_problem', models.TextField(blank=True, default='')),
                ('transfer_problem', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='math_quiz.section')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_quiz', to='math_quiz.sectionsession')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='math_quiz.sectionsession'),
        ),
        migrations.CreateModel(
            name='TeachBackAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('evaluation', models.CharField(blank=True, max_length=40)),
                ('feedback', models.TextField(blank=True)),
                ('follow_up_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_backs', to='math_quiz.sectionsession')),
            ],
        ),
        migrations.CreateModel(
            name='TransferAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('answer', models.TextField()),
                ('reasoning', models.TextField(blank=True, default='')),
                ('confidence', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_attempts', to='math_quiz.sectionsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sectionsession',
            constraint=models.UniqueConstraint(fields=('section', 'browser_session_key'), name='unique_section_browser_session'),
        ),
    ]
