# Generated by Django 6.1 on 2026-08-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0008_unit_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsession',
            name='current_state',
            field=models.CharField(choices=[('FIRST_ATTEMPT', 'First attempt'), ('DIAGNOSIS', 'Diagnosis'), ('VERIFICATION', 'Verification'), ('GUIDED_REVISION', 'Guided revision'), ('TRANSFER_TASK', 'Transfer task'), ('MASTERED', 'Mastered'), ('NEEDS_REVIEW', 'Needs review')], default='FIRST_ATTEMPT', max_length=32),
        ),
        migrations.CreateModel(
            name='UnitDiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='math_quiz.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_quiz.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='math_quiz.unitdiagnosticsession')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='unitdiagnosticsession',
            constraint=models.UniqueConstraint(fields=('unit', 'browser_session_key'), name='unique_unit_browser_diagnostic'),
        ),
    ]
