# Generated by Django 6.1 on 2026-08-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0009_alter_sectionsession_current_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='misconception_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='reasoning_quality',
            field=models.CharField(blank=True, choices=[('STRONG', 'Strong'), ('PARTIAL', 'Partial'), ('WEAK', 'Weak'), ('ABSENT', 'Absent')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_session_key', models.CharField(db_index=True, max_length=40)),
                ('knowledge_score', models.FloatField(default=0)),
                ('transfer_score', models.FloatField(default=0)),
                ('teach_back_score', models.FloatField(blank=True, null=True)),
                ('hint_dependency', models.FloatField(default=0)),
                ('mastery_score', models.FloatField(default=0)),
                ('mastery_state', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('MASTERED', 'Mastered'), ('NEEDS_REVIEW', 'Needs review')], default='NOT_STARTED', max_length=20)),
                ('misconception_type', models.CharField(blank=True, default='', max_length=100)),
                ('misconception_probability', models.FloatField(default=0)),
                ('confidence_calibration', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WELL_CALIBRATED', 'Well calibrated'), ('OVERCONFIDENT', 'Overconfident'), ('UNDERCONFIDENT', 'Underconfident')], default='UNKNOWN', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('hint_count', models.PositiveIntegerField(default=0)),
                ('successful_transfer_count', models.PositiveIntegerField(default=0)),
                ('failed_transfer_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_mastered_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='math_quiz.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'browser_session_key'), name='unique_section_browser_mastery')],
            },
        ),
    ]
