# Generated by Django 6.1 on 2026-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0010_attempt_misconception_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='verification_understanding',
            field=models.CharField(blank=True, choices=[('CLEAR', 'Clear'), ('UNCLEAR', 'Unclear')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sectionsession',
            name='teach_back_level',
            field=models.CharField(blank=True, choices=[('', 'None'), ('SHORT', 'Short'), ('TARGETED', 'Targeted')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sectionsession',
            name='teach_back_level_reason',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teachbackattempt',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teachbackattempt',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionsession',
            name='current_state',
            field=models.CharField(choices=[('FIRST_ATTEMPT', 'First attempt'), ('DIAGNOSIS', 'Diagnosis'), ('VERIFICATION', 'Verification'), ('GUIDED_REVISION', 'Guided revision'), ('TEACH_BACK', 'Teach-Back'), ('TRANSFER_TASK', 'Transfer task'), ('MASTERED', 'Mastered'), ('NEEDS_REVIEW', 'Needs review')], default='FIRST_ATTEMPT', max_length=32),
        ),
    ]
