# Generated by Django 6.1 on 2026-08-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_quiz', '0011_attempt_verification_understanding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='units/materials/')),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='math_quiz.unit')),
            ],
            options={
                'ordering': ('uploaded_at',),
            },
        ),
    ]
