# Generated by Django 6.1 on 2026-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('READING', 'Reading comprehension'), ('WRITTEN', 'Written answer')], max_length=20)),
                ('reference_answer', models.TextField(blank=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
