# Generated by Django 6.1 on 2026-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_quiz', '0003_language_quiz_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagequestion',
            name='title_ja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
