# Generated by Django 6.1 on 2026-08-10 03:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('reasoning', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_session_key', models.CharField(db_index=True, max_length=40)),
                ('current_state', models.CharField(choices=[('TOPIC_SELECTED', 'Topic selected'), ('DIAGNOSTIC_QUIZ', 'Diagnostic quiz'), ('FIRST_ATTEMPT', 'First attempt'), ('RESPONSE_EVALUATION', 'Response evaluation'), ('DIAGNOSIS', 'Diagnosis'), ('GUIDED_REVISION', 'Guided revision'), ('TEACH_BACK', 'Teach-Back'), ('TRANSFER_TASK', 'Transfer task'), ('MASTERED', 'Mastered'), ('NEEDS_REVIEW', 'Needs review')], default='TOPIC_SELECTED', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usage', to='learning_core.learnerattempt')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('reference_answer', models.TextField(blank=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning_core.concept')),
            ],
        ),
        migrations.AddField(
            model_name='learnerattempt',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='learning_core.learningactivity'),
        ),
        migrations.AddField(
            model_name='learnerattempt',
            name='learning_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_core.learningsession'),
        ),
        migrations.CreateModel(
            name='MisconceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('evidence', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconception_records', to='learning_core.concept')),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='learning_core.learningsession')),
            ],
        ),
        migrations.CreateModel(
            name='TeachBackAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('evaluation', models.CharField(blank=True, max_length=40)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_back_attempts', to='learning_core.learningsession')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning_core.subject')),
            ],
        ),
        migrations.AddField(
            model_name='learningsession',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='learning_core.topic'),
        ),
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='learning_core.topic'),
        ),
        migrations.CreateModel(
            name='TransferAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('reasoning', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('used_assistance', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_attempts', to='learning_core.learningactivity')),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_attempts', to='learning_core.learningsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='unique_subject_topic'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.UniqueConstraint(fields=('browser_session_key', 'topic'), name='unique_browser_topic_session'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('topic', 'slug'), name='unique_topic_concept'),
        ),
    ]
