# Generated by Django 6.1 on 2026-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='score_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='total_questions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
