# Generated by Django 6.1 on 2026-08-11 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerattempt',
            name='diagnosis_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learnerattempt',
            name='suspected_misconception',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learnerattempt',
            name='verification_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learnerattempt',
            name='verification_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teachbackattempt',
            name='follow_up_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferattempt',
            name='evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hintusage',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='current_state',
            field=models.CharField(choices=[('TOPIC_SELECTED', 'Topic selected'), ('DIAGNOSTIC_QUIZ', 'Diagnostic quiz'), ('FIRST_ATTEMPT', 'First attempt'), ('RESPONSE_EVALUATION', 'Response evaluation'), ('DIAGNOSIS', 'Diagnosis'), ('VERIFICATION', 'Verification'), ('GUIDED_REVISION', 'Guided revision'), ('TEACH_BACK', 'Teach-Back'), ('TRANSFER_TASK', 'Transfer task'), ('MASTERED', 'Mastered'), ('NEEDS_REVIEW', 'Needs review')], default='TOPIC_SELECTED', max_length=32),
        ),
        migrations.CreateModel(
            name='DiagnosticQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai', 'AI generated'), ('curated', 'Curated fallback')], default='curated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('learning_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_quiz_attempt', to='learning_core.learningsession')),
            ],
        ),
    ]
